FROM node:10.16-jessie

RUN useradd -m -d /home/myuser -s /bin/bash myuser &&\
  apt-get -y update &&\
  apt-get -y install vim curl unzip &&\
  mkdir -p /opt/app/myserver
COPY --chown=myuser:myuser . /opt/app/myserver

USER myuser
WORKDIR /opt/app/myserver

EXPOSE 3000
CMD ["yarn", "start"]
